should fix the bug related to config override within a project's dev-…
teracyhq/dev pull request #427
Opened 2018-04-08 16:33 UTC by phuonglm

2018-05-30 03:55 UTC, datphan approved these changes
working without warning

2018-05-31 20:11 UTC, hoatle commented on lib/utility.rb
> +def overrides(obj1, obj2, debug = false)
I'm not sure about debug here, does it do anything?

2018-05-31 20:12 UTC, hoatle commented
@phuonglm please add unit tests so that we can see the bugs and the tests should be passed with the changes.

2018-05-31 20:13 UTC, hoatle requested changes
changes required

2018-07-25 11:32 UTC, hoatle commented
closed, v0.6.0-a1 will fix this.

2018-07-25 11:32 UTC, closed without merging