@#444 | display tracing
teracyhq/dev pull request #457
Opened 2018-08-27 05:27 UTC by datphan

2018-08-27 08:33 UTC, hoatle requested changes
not the range, but exactly line number of logger call

2018-08-27 08:33 UTC, hoatle commented on lib/teracy-dev/logging.rb
> +          tracing = TeracyDev::Common.light_gray("\n#{caller[3..10] ? caller[3..10].join("\n") : caller}\n")
we'd like to know exactly the line number of logger call, not the range.

2018-08-31 06:06 UTC, datphan commented on lib/teracy-dev/logging.rb
> +          tracing = TeracyDev::Common.light_gray("\n#{caller[3]}\n")
@hoatle 
```
/Users/datphan/teracy/k8s-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/provisioners.rb:12:in `block in configure_node'
```
is this what you mean?

2018-08-31 06:27 UTC, hoatle approved these changes
LGTM

2018-08-31 06:27 UTC, merged