@ #497 | should support register with weight
teracyhq/dev pull request #512
Opened 2018-10-21 11:09 UTC by hieptranquoc

please check this PR, thank you!

2018-10-22 10:12 UTC, datphan commented
I think we should try this: http://ruby-doc.org/core-2.2.2/Enumerable.html#method-i-sort_by

2018-10-23 20:41 UTC, hieptranquoc commented
@datphan I've updated, please check this PR again!

2018-10-24 02:50 UTC, datphan commented on lib/teracy-dev/config/manager.rb
> +          @logger.warn("Weight must be integer, otherwise weight will be set to default(5)")
should be `"#{configurator}'s weight must be integer, ..."`

2018-10-24 04:36 UTC, datphan submitted a review, later dismissed

2018-10-24 07:22 UTC, hoatle requested changes
@hieptranquoc pls check my comments

2018-10-24 07:22 UTC, hoatle commented on lib/teracy-dev/config/manager.rb
> +          @logger.warn("Weight must be integer, otherwise weight will be set to default(5)")
weight must be an integer within 0-9 range, make sure to validate that.
- not set: default 5
- wrong type or wrong value => add warn and set default 5

2018-10-24 07:22 UTC, hoatle commented on lib/teracy-dev/processors/manager.rb
> +        @processors = Array.new
`@processors = []` is shorter, it's the same with Array.new, there is no reason to change this

2018-10-24 07:22 UTC, hoatle commented on lib/teracy-dev/processors/manager.rb
> +          @logger.warn("Weight must be integer, otherwise weight will be set to default(5)")
message should show which processor has this warning (refer to @datphan's comment)

2018-10-24 07:22 UTC, hoatle commented on lib/teracy-dev/loader.rb
> +      @configManager.sort_configurator_by_weight
move this logic out of loader, to the configManager instead

2018-10-24 07:22 UTC, hoatle commented on lib/teracy-dev/loader.rb
> +      @processorsManager.sort_processor_by_weight
move this logic to processorsManager instead

2018-10-24 07:22 UTC, hoatle commented on lib/teracy-dev/config/manager.rb
> -        @configurators << configurator
I prefer this to store the original registered order
```
@configurators << [configurator, weight]
```

Then from the process method, we sort it by the specified requirements and call each configurator, this should make sure the logic is clear, we could change the sort requirement later without having changing the logic in mind, just update the sort function.

2018-10-24 07:23 UTC, hoatle commented
@datphan not sure why you approved this when this is not good enough.

2018-10-24 07:29 UTC, hoatle commented on lib/teracy-dev/config/manager.rb
> -        @configurators << configurator
this helps to debug a lot, too.

2018-10-24 12:15 UTC, hieptranquoc commented
@hoatle please check again! I've updated.

2018-10-24 13:08 UTC, hoatle commented on lib/teracy-dev/config/manager.rb
> +          @configurators.concat(val)
don't change the original configurators

2018-10-24 13:08 UTC, hoatle commented on lib/teracy-dev/config/manager.rb
> +        @configurators << { configurator: configurator, weight: weight }
try this: https://stackoverflow.com/questions/28234803/ruby-sort-by-multiple-fields-and-multilple-directions-for-different-data-types

processors << [id: processors.length, processor: processor, weight: weight]

and to sort with our requirement:

sorted_processors = multi_sort(processors, id: :asc, weight: :desc)

2018-10-24 13:10 UTC, hoatle commented on lib/teracy-dev/processors/manager.rb
>          @processors.each do |processor|
`Util.multi_sort(@processors, id: :acs, weight: :desc).each do |processor|`

2018-10-24 17:42 UTC, hieptranquoc commented
@hoatle I've updated! Please check again!

2018-10-24 18:40 UTC, hoatle approved these changes
LGTM, merging and I'll do some clean up

2018-10-24 18:40 UTC, merged