@ #501 | should support id update with deprecation
teracyhq/dev pull request #538
Opened 2018-11-01 09:43 UTC by hieptranquoc

connect #501 
please check PR! thank you

2018-11-01 10:43 UTC, hieptranquoc commented
@hoatle I've updated, please check this PR again!

2018-11-01 16:47 UTC, datphan submitted a review, later dismissed

2018-11-02 01:33 UTC, hoatle requested changes
@hieptranquoc pls check my comment

2018-11-02 01:33 UTC, hoatle commented on lib/teracy-dev/util.rb
> +                    @@logger.warn("The _id: #{val1['_id_deprecated']} is deprecated, use the _id: #{val1['_id']} instead")
@@logger.warn("The _id: '#{val1['_id_deprecated']}' is deprecated, use the _id: '#{val1['_id']}' instead for #{val}")

2018-11-02 01:33 UTC, hoatle commented on lib/teracy-dev/util.rb
> +                    @@logger.warn("The _id: #{val1['_id_deprecated']} is deprecated, use the _id: #{val1['_id']} instead")
something wrong, I expect 1 time of the warning only, got 2 times:

```
$ vagrant status
[TeracyDev::Util][WARN]: The _id: '0' is deprecated, use the _id: 'kernel-core' instead for {"_id"=>"0", "location"=>{"git"=>{"remote"=>{"origin"=>"https://github.com/teracyhq-incubator/teracy-dev-core.git"}, "branch"=>"develop"}}, "require_version"=>">= 0.4.0-SNAPSHOT", "enabled"=>true}
/Users/hoatle/teracy-dev/lib/teracy-dev/util.rb:220:in `block (3 levels) in override'

[TeracyDev::Util][WARN]: The _id: '0' is deprecated, use the _id: 'kernel-core' instead for {"_id"=>"0", "location"=>{"git"=>{"remote"=>{"origin"=>"https://github.com/teracyhq-incubator/teracy-dev-core.git"}, "branch"=>"develop"}}, "require_version"=>">= 0.4.0-SNAPSHOT", "enabled"=>true}
/Users/hoatle/teracy-dev/lib/teracy-dev/util.rb:220:in `block (3 levels) in override'
```

2018-11-05 02:49 UTC, hoatle approved these changes
LGTM, will do some minor clean up

2018-11-05 02:49 UTC, merged