@ #492 | should mask specified sensitive values within log messages
teracyhq/dev pull request #551
Opened 2018-11-09 21:22 UTC by hieptranquoc

connect #492 
please check this PR, thank you!

2018-11-09 21:23 UTC, hieptranquoc commented
config:
```
logger:
  masked_values: ['some value', 'another value']
```

2018-11-10 03:39 UTC, hoatle requested changes
@hieptranquoc pls check my comments, basically, this is what I'm expected, just need to name functions, variables more clearly and properly.

2018-11-10 03:39 UTC, hoatle commented on lib/teracy-dev/logging/mask_log_manager.rb
> +      @log_masked = {}
masked_values

2018-11-10 03:39 UTC, hoatle commented on lib/teracy-dev/logging/mask_log_manager.rb
> +      def self.add_log_masked(value)
add_masked_values(values)

2018-11-10 03:39 UTC, hoatle commented on lib/teracy-dev/logging/mask_log_manager.rb
> +      def self.mask_log(msg)
def self.masked(msg)

2018-11-10 03:39 UTC, hoatle commented on lib/teracy-dev/loader.rb
> +    def add_log_filter(value)
def add_masked_values

2018-11-10 03:41 UTC, hoatle commented
Need to add `TeracyDev.add_logger_masked_values` api so that other extensions can call this api dynamically, don't forget to update this api docs: what it does and how to use, @since v0.6.0-a5 and any reference (for example, link to the related issue)

2018-11-13 09:44 UTC, hieptranquoc commented
@hoale please check this PR again! thank you!

2018-11-13 09:45 UTC, hieptranquoc commented
@hoatle please check this PR again! Thank you

2018-11-13 15:23 UTC, hieptranquoc commented
@hoatle I've updated! Please check this PR again. Thank you!

2018-11-14 00:56 UTC, hoatle commented
did not work as expected:

- config_default.yaml

```yaml
variables:
  entry_secret: ${ENTRY_SECRET:-abcdef}
```

- logger.yaml

```yaml
logger:
  masked_values: ["%{entry_secret}"]
```

```shell
$ LOG_LEVEL=debug vagrant status | grep abcdef
[TeracyDevCore::Processors::Variables][DEBUG]: KEY: entry_secret, env_key: ENTRY_SECRET, env_value: , env_default: abcdef
```

expected: `env_default: ******`

```shell
$ ENTRY_SECRET=hello LOG_LEVEL=debug vagrant status | grep hello
[TeracyDevCore::Processors::Variables][DEBUG]: KEY: entry_secret, env_key: ENTRY_SECRET, env_value: hello, env_default: abcdef
```
expected: `env_value: *****`

- `@logger.debug("abcdef")` was not masked

```shell
$ LOG_LEVEL=debug vagrant status | grep abcdef
[TeracyDevCore::Processors::Variables][DEBUG]: KEY: entry_secret, env_key: ENTRY_SECRET, env_value: , env_default: abcdef
[TeracyDevCore::Config::Networks][DEBUG]: abcdefd
```

2018-11-14 12:10 UTC, hieptranquoc commented
@hoatle I've updated! Please check this PR again! Thank you!

2018-11-14 12:11 UTC, hieptranquoc commented
original config:
```yaml
logger:
  mask:
    keys: {}
    values: []
```
example override config in config_override.yaml
```yaml
logger:
  mask:
    keys:
      node_name_prefix: ${NODE_NAME_PREFIX:-node}
      node_hostname_prefix: ${NODE_HOSTNAME_PREFIX:-k8s}
      node_domain_affix: ${NODE_DOMAIN_AFFIX:-local}
      iorad_app_github_username: ${IORAD_GITHUB_USERNAME:-tada-todo | tudu}
      iorad_app_github_password: "012345678"
      iorad_app_env_var: ${IORAD_APP_ENV_VAR}
    values: [settings, configure]
```

2018-11-15 01:46 UTC, hoatle commented
@hieptranquoc still very buggy

```
logger.yaml:

```
logger:
  mask:
    variables:
      entry_secret: ${ENTRY_SECRET:-abcdef}
```

config_override.yaml

```
variables:
  entry_secret: hi
```


logger.debug("test hello abcdef hi")

expected: "test hello abcdef **"
actual: "test hello ***** **"
```

2018-11-15 01:48 UTC, hoatle commented
notes:
```
# - Build logger.mask
#   + load logger.yaml if any
#   + load config_override.yaml if any
#   + override "logger.mask.variables" from logger.yaml with "variables" from config_override.yaml if any
# - Resolve mask.variables to mask.values if logger.mask.variables exists then append values to MaskManager
#   + how to resolve: https://github.com/teracyhq-incubator/teracy-dev-core/blob/develop/lib/teracy-dev-core/processors/variables.rb#L14
# - Logger will ask MaskManager to mask its log message
```
notes:
```
- no teracy-dev-entry/logger.yaml => do nothing
- teracy-dev-entry/logger.yaml avaiable only => load and validate and then resolve logger.mask.variables
- teracy-dev-entry/config_override.yaml avaiable => load and validate and override logger.mask.variables from logger.yaml with variables from config_override.yaml and then resolve logger.mask.variables
```

2018-11-15 06:01 UTC, hoatle commented
@hieptranquoc this case failed (the same setup from https://github.com/teracyhq/dev/pull/551#issuecomment-438885667)

with config_override.yaml and $ ENTRY_SECRET=hello LOG_LEVEL=debug vagrant status
expected: "test *** abcdef hi"
actual: "test ***** abcdef **" => KO

2018-11-15 07:38 UTC, hieptranquoc commented
@hoatle I've updated! Please check again. Thank you!

2018-11-15 08:56 UTC, hoatle commented
@hieptranquoc this case failed when
config_override.yaml

```
variables:
  entry_secret: hi
```

expected: "test hello abcdef **"
actual: "test hello ****** **"

2018-11-15 09:46 UTC, hieptranquoc commented
@hoatle I've updated! Please check again! Sr for wasting your time. Thank you!

2018-11-15 09:51 UTC, hoatle approved these changes
passed by basic test cases, will improve more later.

2018-11-15 09:52 UTC, merged