should run location sync with specific vagrant sub commands only to i…
teracyhq/dev pull request #554
Opened 2018-11-15 07:25 UTC by phuonglm

connect #531

2018-11-15 07:30 UTC, datphan submitted a review, later dismissed

2018-11-15 09:12 UTC, hoatle requested changes
@phuonglm pls check my comments

2018-11-15 09:12 UTC, hoatle commented on lib/teracy-dev/extension/manager.rb
> +        if Util.cmdRequireSync?
move this condition into Location::Manager.sync instead, add optional argument force=false; if force = true and Util.cmdRequireSync? is false => continue syncing

`
Location::Manager.sync(location, sync_existing, force=False)
`

2018-11-15 09:12 UTC, hoatle commented on lib/teracy-dev/extension/manager.rb
> +          @logger.error("manifest for extension #{extension['path']['extension']} not found, seem you not sync all required extension. Please run vagrant <status|up|reload> to sync it first.")
@logger.error("manifest for extension #{extension['path']['extension']} not found, seem that you haven't synced all the required extensions. Please run vagrant <status|up|reload> to sync them first")

2018-11-15 09:12 UTC, hoatle commented on lib/teracy-dev/loader.rb
> +      if Util.cmdRequireSync? && Location::Manager.sync(location, location['sync']) == true
don't change this, Location::Manager.sync should be updated only

2018-11-15 09:12 UTC, hoatle commented on lib/teracy-dev/util.rb
> +    def self.cmdRequireSync?
move this into Location::Manager.sync as private for now

2018-11-16 01:14 UTC, phuonglm commented
I updated the PR.

2018-11-16 01:24 UTC, hoatle approved these changes
LGTM, I'll update `cmdRequireSync` to `sync_required?`

2018-11-16 01:24 UTC, hoatle commented on lib/teracy-dev/location/manager.rb
> +      def self.cmdRequireSync?
follow convention for method name (snake case instead of camel case), `sync_required?` is good name to me

2018-11-16 01:25 UTC, merged