@ #492 | fix msg is not string bug
teracyhq/dev pull request #564
Opened 2018-11-27 03:56 UTC by datphan

2018-11-27 08:11 UTC, hieptranquoc submitted a review, later dismissed

2018-11-27 08:20 UTC, hoatle commented
https://github.com/teracyhq/dev/blob/develop/lib/teracy-dev/logging.rb#L62 is the line should be the place for bug fix, not on the mask_filter file.

2018-11-27 08:21 UTC, hoatle requested changes
not the right place for fix

2018-11-28 04:12 UTC, datphan commented on lib/teracy-dev/logging.rb
> +            msg = filter.filtered(msg.to_s)
@hoale updated, pls check again

2018-11-28 04:25 UTC, hoatle approved these changes
LGTM

2018-11-28 04:26 UTC, merged