#565 | how to add export env var
teracyhq/dev pull request #566
Opened 2018-11-27 04:58 UTC by hoavt

2018-12-02 10:01 UTC, hoatle requested changes
@hoavt pls check my comments, you always should open the .rst file on github to see the output result to prevent these kinds of mentioned problems.

2018-12-02 10:01 UTC, hoatle commented on docs/getting_started.rst
> +      - On Windows, you must always use ``Cygwin Terminal``, not ``Git Bash
not \``Git Bash``.

2018-12-02 10:01 UTC, hoatle commented on docs/getting_started.rst
> +        `export VAGRANT_PREFER_SYSTEM_BIN=true` environment variable to the `./bash_profile` file, that helps you
\``export VAGRANT_PREFER_SYSTEM_BIN=true``

\``.bash_profile``

2018-12-02 10:01 UTC, hoatle commented on docs/getting_started.rst
> +      Now, open the terminal and run the `export` command to check if the variable is added successfully
\``export``

2018-12-03 00:10 UTC, hoavt commented
Applied your comments. Please check @hoatle.

2018-12-03 02:53 UTC, hoatle approved these changes
LGTM

2018-12-03 02:53 UTC, merged